package parser;

import language.Grammar;

public interface Parser {

    String getName();

    /**
     * Decide whether a given phrase belongs to the language generated by the given grammar.
     *
     * @param grammar a context-free grammar (in Chomsky normal form)
     * @param phrase  a string array representing a phrase
     * @return true if the phrase belongs to the language, false otherwise
     */
    boolean belongsToLanguage(Grammar grammar, String[] phrase);

    /**
     * Decide whether a given phrase belongs to the language generated by the given grammar.
     *
     * @param phrase a string array representing a phrase
     * @return true if the phrase belongs to the language, false otherwise
     */
    boolean belongsToLanguage(String[] phrase);
}
